"use client";
import {ChevronDown,ChevronRight,Folder,GripVertical,Image as ImageIcon,Inbox,PanelRightClose,PanelRightOpen,Plus,Star,Trash2,Upload,X} from "lucide-react";
import {useEffect,useMemo,useRef,useState} from "react";
type FolderNode={id:string;name:string;parentId:string|null;collapsed:boolean;order:number};
type Asset={id:string;name:string;dataUrl:string;folderId:string|null;note:string;starred:boolean;createdAt:string;size:number};
type Scope="all"|"uncategorized"|"starred"|string;
const uid=()=>`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const defaults:FolderNode[]=[
 {id:"affairs",name:"事务",parentId:null,collapsed:false,order:0},{id:"deadline",name:"截止",parentId:"affairs",collapsed:false,order:0},{id:"task",name:"行动",parentId:"affairs",collapsed:false,order:1},
 {id:"career",name:"求职",parentId:null,collapsed:false,order:1},{id:"job",name:"岗位",parentId:"career",collapsed:false,order:0},
 {id:"learning",name:"学习",parentId:null,collapsed:false,order:2},{id:"knowledge",name:"知识",parentId:"learning",collapsed:false,order:0},{id:"resource",name:"资源",parentId:"learning",collapsed:false,order:1},
 {id:"project",name:"项目",parentId:null,collapsed:false,order:3},{id:"personal",name:"个人",parentId:null,collapsed:false,order:4},{id:"contact",name:"人物",parentId:"personal",collapsed:false,order:0},{id:"record",name:"记录",parentId:"personal",collapsed:false,order:1},
];
export default function SignalWorkspace(){
 const [folders,setFolders]=useState<FolderNode[]>(defaults),[assets,setAssets]=useState<Asset[]>([]),[scope,setScope]=useState<Scope>("all"),[selectedId,setSelectedId]=useState(""),[rightOpen,setRightOpen]=useState(false),[dragFolder,setDragFolder]=useState(""),[dragAsset,setDragAsset]=useState(""),[dragOver,setDragOver]=useState(""),[toast,setToast]=useState(""),[ready,setReady]=useState(false);const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{try{const savedFolders=localStorage.getItem("signal-mvp-folders"),savedAssets=localStorage.getItem("signal-mvp-assets"),old=localStorage.getItem("signal-categories");if(savedFolders)setFolders(JSON.parse(savedFolders));else if(old){const custom=JSON.parse(old) as Array<{id:string;label:string;parentId:string}>;const parentMap:Record<string,string|null>={事务:"affairs",求职:"career",学习:"learning",项目:"project",个人:"personal",root:null};setFolders([...defaults,...custom.map((c,i)=>({id:c.id,name:c.label,parentId:parentMap[c.parentId]??c.parentId,collapsed:false,order:defaults.length+i}))])}if(savedAssets)setAssets(JSON.parse(savedAssets));}catch{}setReady(true)},[]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem("signal-mvp-folders",JSON.stringify(folders));localStorage.setItem("signal-mvp-assets",JSON.stringify(assets))}catch{notify("浏览器存储空间不足，请删除部分大图")}},[folders,assets,ready]);
 const selected=assets.find(a=>a.id===selectedId),visible=useMemo(()=>assets.filter(a=>scope==="all"?true:scope==="uncategorized"?!a.folderId:scope==="starred"?a.starred:a.folderId===scope),[assets,scope]);
 const notify=(m:string)=>{setToast(m);setTimeout(()=>setToast(""),1600)};const patchAsset=(id:string,p:Partial<Asset>)=>setAssets(v=>v.map(a=>a.id===id?{...a,...p}:a));
 function upload(files:FileList|null){if(!files)return;const images=Array.from(files).filter(f=>f.type.startsWith("image/"));if(!images.length){notify("第一轮只支持图片文件");return}Promise.all(images.map(file=>new Promise<Asset>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({id:uid(),name:file.name,dataUrl:String(reader.result),folderId:null,note:"",starred:false,createdAt:new Date().toISOString(),size:file.size});reader.onerror=reject;reader.readAsDataURL(file)}))).then(result=>{setAssets(v=>[...result,...v]);setSelectedId(result[0].id);setScope("uncategorized");setRightOpen(true);notify(`已上传 ${result.length} 张图片，放入未分类`)}).catch(()=>notify("图片读取失败"))}
 function addFolder(parentId:string|null){const name=prompt(parentId?"子文件夹名称":"文件夹名称");if(name?.trim())setFolders(v=>[...v,{id:uid(),name:name.trim(),parentId,collapsed:false,order:v.length}])}
 function descendants(id:string):string[]{const direct=folders.filter(f=>f.parentId===id).map(f=>f.id);return direct.flatMap(x=>[x,...descendants(x)])}
 function dropFolder(targetId:string|null){if(!dragFolder)return;if(targetId===dragFolder||targetId&&descendants(dragFolder).includes(targetId)){setDragFolder("");return}setFolders(v=>v.map(f=>f.id===dragFolder?{...f,parentId:targetId}:f));setDragFolder("");setDragOver("")}
 function dropAsset(folderId:string|null){if(!dragAsset)return;patchAsset(dragAsset,{folderId});setDragAsset("");setDragOver("");notify(folderId?"已归入文件夹":"已移到未分类")}
 function renderTree(parentId:string|null,depth=0):React.ReactNode{return folders.filter(f=>f.parentId===parentId).sort((a,b)=>a.order-b.order).map(f=>{const hasChild=folders.some(x=>x.parentId===f.id);return <div key={f.id}><div className={`folder-row ${scope===f.id?"active":""} ${dragOver===f.id?"drop-target":""}`} style={{paddingLeft:9+depth*16}} draggable onDragStart={e=>{e.stopPropagation();setDragFolder(f.id);e.dataTransfer.effectAllowed="move"}} onDragOver={e=>{e.preventDefault();e.stopPropagation();setDragOver(f.id)}} onDragLeave={()=>setDragOver("")} onDrop={e=>{e.preventDefault();e.stopPropagation();dragAsset?dropAsset(f.id):dropFolder(f.id)}} onClick={()=>setScope(f.id)}><button onClick={e=>{e.stopPropagation();setFolders(v=>v.map(x=>x.id===f.id?{...x,collapsed:!x.collapsed}:x))}}>{hasChild?(f.collapsed?<ChevronRight/>:<ChevronDown/>):<span/>}</button><Folder/><span>{f.name}</span><em>{assets.filter(a=>a.folderId===f.id).length}</em><button className="folder-plus" onClick={e=>{e.stopPropagation();addFolder(f.id)}}><Plus/></button></div>{!f.collapsed&&renderTree(f.id,depth+1)}</div>})}
 function removeAsset(id:string){setAssets(v=>v.filter(a=>a.id!==id));setSelectedId("");setRightOpen(false);notify("素材已删除")}
 const scopeTitle=scope==="all"?"全部素材":scope==="uncategorized"?"未分类素材":scope==="starred"?"星标素材":folders.find(f=>f.id===scope)?.name||"素材";
 return <main className="mvp-app"><aside className="mvp-sidebar"><header><div>S</div><strong>Signal</strong></header><button className="upload-button" onClick={()=>fileRef.current?.click()}><Upload/>上传素材</button><input ref={fileRef} hidden type="file" accept="image/*" multiple onChange={e=>{upload(e.target.files);e.target.value=""}}/><nav><button className={scope==="all"?"active":""} onClick={()=>setScope("all")}><ImageIcon/><span>全部素材</span><em>{assets.length}</em></button><button className={`${scope==="uncategorized"?"active":""} ${dragOver==="uncategorized"?"drop-target":""}`} onDragOver={e=>{e.preventDefault();setDragOver("uncategorized")}} onDrop={e=>{e.preventDefault();dropAsset(null)}} onClick={()=>setScope("uncategorized")}><Inbox/><span>未分类素材</span><em>{assets.filter(a=>!a.folderId).length}</em></button><button className={scope==="starred"?"active":""} onClick={()=>setScope("starred")}><Star/><span>星标素材</span><em>{assets.filter(a=>a.starred).length}</em></button></nav><section className="folder-tree"><header><span>文件夹</span><button onClick={()=>addFolder(null)}><Plus/></button></header>{renderTree(null)}</section><footer>无需登录 · 数据保存在当前浏览器</footer></aside>
 <section className="asset-list"><header><div><small>Signal / 素材</small><h1>{scopeTitle}</h1></div><div><button className="header-upload" onClick={()=>fileRef.current?.click()}><Plus/>上传素材</button><button title={rightOpen?"收起右栏":"打开右栏"} onClick={()=>setRightOpen(v=>!v)}>{rightOpen?<PanelRightClose/>:<PanelRightOpen/>}</button></div></header><div className="asset-count">{visible.length} 个素材</div><div className="assets">{visible.map(a=><button className={`asset-row ${selectedId===a.id?"selected":""}`} key={a.id} draggable onDragStart={e=>{setDragAsset(a.id);e.dataTransfer.effectAllowed="move"}} onClick={()=>{setSelectedId(a.id);setRightOpen(true)}}><GripVertical className="asset-grip"/><img src={a.dataUrl} alt=""/><span><strong>{a.name}</strong><small>{new Date(a.createdAt).toLocaleString("zh-CN")}</small></span>{a.starred?<Star className="starred"/>:null}</button>)}{!visible.length?<div className="asset-empty"><ImageIcon/><strong>{scope==="uncategorized"?"没有未分类素材":"还没有图片素材"}</strong><p>点击“上传素材”添加单张或多张截图</p></div>:null}</div></section>
 <aside className={`asset-detail ${rightOpen&&selected?"open":""}`}>{selected?<><header><button onClick={()=>setRightOpen(false)}><X/></button><strong>素材详情</strong></header><div className="preview"><img src={selected.dataUrl} alt={selected.name}/></div><div className="detail-body"><input className="asset-name" value={selected.name} onChange={e=>patchAsset(selected.id,{name:e.target.value})}/><label>配套笔记<textarea value={selected.note} onChange={e=>patchAsset(selected.id,{note:e.target.value})} placeholder="记录这张截图为什么有用、以后如何使用……"/></label></div><footer><select value={selected.folderId||""} onChange={e=>patchAsset(selected.id,{folderId:e.target.value||null})}><option value="">未分类</option>{folders.map(f=><option key={f.id} value={f.id}>{`${"　".repeat(f.parentId?1:0)}${f.name}`}</option>)}</select><button className={selected.starred?"active":""} onClick={()=>patchAsset(selected.id,{starred:!selected.starred})}><Star/>星标</button><button className="delete" onClick={()=>removeAsset(selected.id)}><Trash2/>删除</button></footer></>:null}</aside>{toast?<div className="mvp-toast">{toast}</div>:null}</main>
}
